### ISSUE TITLE
staccato and tenuto

### ISSUE THREAD

**Issue by Jaimyy** [grame-cncm/guidodoc#1]
I cannot use both staccato and tenuto on more than one note at the same time.

{[  \clef<"g2"> \key<0> 

   g2/8  _/8
   \stacc(\ten(g2/8)) _/8
   \stacc(\marcato(g2/8)) _/8   
   \stacc(\accent(g2/8)) _/8 
   \stacc(\mord(g2/8)) _/8\bar 

   {e2/8, g2/8}  _/8
   \stacc(\ten({e2/8, g2/8})) _/8
   \stacc(\marcato({e2/8, g2/8})) _/8   
   \stacc(\accent({e2/8, g2/8})) _/8 
   \stacc(\mord({e2/8, g2/8})) _/8\bar  
   
    {e2/8, g2/8}  _/8
   \ten(\stacc({e2/8, g2/8})) _/8
   \marcato(\stacc({e2/8, g2/8})) _/8   
   \accent(\stacc({e2/8, g2/8})) _/8 
   \mord(\stacc({e2/8, g2/8})) _/8\bar 
   
   \stacc({e2/8, g2/8})  _/8 
   \ten({e2/8, g2/8}) _/8   
   {\ten(e2/8), \stacc(g2/8)} _/8
   {\stacc(e2/8), \ten(g2/8)} _/8 
   {\stacc(e2/8), \mord(g2/8)} _/8\bar 
    ]}
![grafik](https://user-images.githubusercontent.com/103506613/162965284-45ee9b3c-c435-43e6-b1ae-076609656ddc.png)

**Comment by domfober** [comment]
You should post this issue to the guidolib project (https://github.com/grame-cncm/guidolib/issues).
I also recommend you to isolate the issue and post a minimal example.

**Comment by Jaimyy** [comment]
Thanks for comment!
