### ISSUE TITLE
Notes guide page is incomplete

### ISSUE THREAD

**Issue by SirPL** [grame-cncm/guidodoc#2]
Reading the https://guidodoc.grame.fr/guide/notes/#duration page I noticed it's not fully rendered.

It mainly due to the fact there's no closing `</script>` tag in:
https://github.com/grame-cncm/guidodoc/blob/master/docs/guide/notes/index.html#L387

Also, `<line>` tags right below JavaScript code are either misplaced or should be wrapped with `<svg>`?

**Comment by dfober** [comment]
Fixed. I had to remove the last inline svg example. Actually the pages are generated by mkdocs and it cannot insert this example correctly (the result is a mix the BNF code and the svg code with missing closing tags). 
Thanks for the issue.
